### ISSUE TITLE
libx64

### ISSUE THREAD

**Issue by likfe** [SinaVDDeveloper/demo#1]
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cc.lait.d2.i4movies-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]] couldn't find "libsinit.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:989)
            at com.sina.sinavideo.coreplayer.splayer.SPlayer.<clinit>(SPlayer.java:371)
            at com.sina.sinavideo.sdk.utils.VDApplication.initPlayer(VDApplication.java:29)
            at cc.lait.d2.i4movies.App.onCreate(App.java:15)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4621)
            at android.app.ActivityThread.access$1500(ActivityThread.java:154)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5336)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by onecoders** [comment]
这个是没有64bit的支持，我也遇到了

**Comment by likfe** [comment]
貌似本仓库长期无维护状态，关闭此issue
